<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="estilo.css"?>
<!DOCTYPE recetario[
<!ELEMENT recetario (receta+)>
<!ELEMENT receta (nombre_receta,ingredientes,preparacion)>
<!ELEMENT nombre_receta (#PCDATA) >
<!ELEMENT ingredientes (#PCDATA) >
<!ELEMENT preparacion (#PCDATA) >
]>
<recetario>
    <receta>
        <nombre_receta>Pudín de Banana y Chocolate</nombre_receta>
        <ingredientes>    3 bananas. 
            4 cdas. de crema de leche.
            250 g de chocolate untable.</ingredientes>
        <preparacion>
            Pela las bananas y en un recipiente tritúralas con un tenedor.
            Mezcla la crema de leche con el chocolate untable. 
            Añade el "puré de banana" a la mezcla de chocolate.
            Reserva en el refrigerador por una hora y disfruta junto a ellos de una sencilla delicia. 
        </preparacion>
    </receta>
    <receta>
        <nombre_receta>Dip de limón</nombre_receta>
        <ingredientes>    El zumo de 4 limones grandes.
            4 cdas. de miel.
            250 g de yogurt griego.
            Rayadura de una cáscara de limón.</ingredientes>
        <preparacion>
            Mezcla el zumo de limón con la miel hasta conseguir una sustancia homogénea.
            Añade, poco a poco y sin dejar de batir, el yogurt a la mezcla de limón y miel.
            Vierte en pequeños recipientes la mezcla que acabas de preparar.
            Decora con un poco de ralladura de limón. También puedes agregar un fruto rojo como ves en la fotografía.
            Reserva en el refrigerador durante 1 hora. Retira y disfruta del dulce sabor de este postre.
        </preparacion>
    </receta>    
   
    
</recetario>
